(function(){
'use strict';
const $=s=>document.querySelector(s);
const $$=s=>Array.from(document.querySelectorAll(s));
const hasBaseData=typeof F!=='undefined'&&typeof H!=='undefined'&&typeof S!=='undefined';
if(!hasBaseData){const main=document.querySelector('main');if(main)main.innerHTML='<div class="notice"><b>تعذر تحميل بيانات الخريطة.</b> أعد فتح الصفحة.</div>';return;}
const baseFacilities=F.map(([n,name,cat,desc,family,hours,confirmed])=>({n,name,cat,desc,family,hours,confirmed:!!confirmed}));
const baseSchedules=S.map(([name,time,verified,note])=>({name,time,verified:!!verified,note}));
const oldCounts=new Map();H.forEach(h=>oldCounts.set(h[0],(oldCounts.get(h[0])||0)+1));
function uniqueByNumber(list){const seen=new Set();return list.filter(h=>{if(seen.has(h[0]))return false;seen.add(h[0]);return true;});}
const complexHotspots={park:uniqueByNumber(H.filter(h=>h[1]>=57)),blu:uniqueByNumber(H.filter(h=>h[1]<=60))};
const officialData=window.AQUAPARK_OFFICIAL;if(!officialData)return;
const officialFacilities=officialData.facilities,officialPx=officialData.hotspots,officialRooms=officialData.rooms,complexRooms=officialData.complexRooms;
const officialByNumber=new Map(officialFacilities.map(f=>[f.n,f]));
const config={park:{name:'بيكالباتروس أكوا بارك',short:'أكوا بارك',pools:25,heated:4},blu:{name:'بيكالباتروس أكوا بلو',short:'أكوا بلو',pools:25,heated:4}};
const state={resort:'park',mapKind:'official',mode:'facilities',zoom:1,lastArea:'official',category:'الكل',imageToken:0};
const els={stage:$('#stage'),viewport:$('#viewport'),image:$('#mapImage'),detail:$('#detail'),sheet:$('#sheet'),zoom:$('#zoomInfo'),grid:$('#facilityGrid'),filters:$('#filters'),search:$('#search'),events:$('#eventGrid'),rooms:$('#roomGrid')};
if(!els.stage||!els.viewport||!els.image)return;
function openView(id){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));window.scrollTo({top:0,behavior:'smooth'});}
$$('.tab').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.view)));
function setZoom(value,keepCenter=true){const oldW=els.stage.scrollWidth||els.viewport.clientWidth||1,cx=els.viewport.scrollLeft+els.viewport.clientWidth/2,cy=els.viewport.scrollTop+els.viewport.clientHeight/2;state.zoom=Math.max(1,Math.min(4,value));els.stage.style.width=(state.zoom*100)+'%';if(els.zoom)els.zoom.textContent='التكبير: '+Math.round(state.zoom*100)+'٪';if(keepCenter)requestAnimationFrame(()=>{const ratio=(els.stage.scrollWidth||oldW)/oldW;els.viewport.scrollLeft=Math.max(0,cx*ratio-els.viewport.clientWidth/2);els.viewport.scrollTop=Math.max(0,cy*ratio-els.viewport.clientHeight/2);});}
function centerAt(x,y){requestAnimationFrame(()=>{els.viewport.scrollLeft=Math.max(0,els.stage.scrollWidth*x/100-els.viewport.clientWidth/2);els.viewport.scrollTop=Math.max(0,els.stage.scrollHeight*y/100-els.viewport.clientHeight/2);});}
function focusPoint(point){const[x,y,z]=point;setZoom(innerWidth<700?z:Math.max(1.35,z-.55),false);setTimeout(()=>centerAt(x,y),40);}
function showSheet(){if(innerWidth<=850&&els.sheet){els.sheet.classList.add('open');els.sheet.setAttribute('aria-hidden','false');}}
function closeSheet(){if(els.sheet){els.sheet.classList.remove('open');els.sheet.setAttribute('aria-hidden','true');}}
const closeBtn=$('#closeSheet');if(closeBtn)closeBtn.addEventListener('click',closeSheet);if(els.sheet)els.sheet.addEventListener('click',e=>{if(e.target===els.sheet)closeSheet();});
function fillSheet(symbol,cat,title,desc,extra,status){const values={sheetNumber:symbol,sheetCat:cat,sheetTitle:title,sheetDesc:desc,sheetFamily:extra,sheetHours:status};Object.entries(values).forEach(([id,v])=>{const el=$('#'+id);if(el)el.textContent=v;});}
function getFacility(n){return state.mapKind==='official'?officialByNumber.get(Number(n)):baseFacilities.find(f=>f.n===Number(n));}
function facilityCount(n){return state.mapKind==='official'?officialPx.filter(x=>x[0]===Number(n)).length:(oldCounts.get(Number(n))||1);}
function showFacility(n){const f=getFacility(n);if(!f)return;$$('.marker').forEach(m=>m.classList.toggle('selected',m.dataset.number===String(n)));const repeat=facilityCount(n),repeatHtml=repeat>1?'<div class="detail-row"><b>تعدد المواقع</b>يظهر هذا المرفق في '+repeat+' مواقع على الخريطة.</div>':'';if(els.detail)els.detail.innerHTML='<div class="detail-symbol">'+f.n+'</div><span class="pill">'+f.cat+'</span><h2>'+f.name+'</h2><p>'+f.desc+'</p><div class="detail-row"><b>مناسبته للعائلة</b>'+f.family+'</div><div class="detail-row"><b>التشغيل أو الحالة</b><span class="hour '+(f.confirmed?'ok':'')+'">'+f.hours+'</span></div>'+repeatHtml;fillSheet(f.n,f.cat,f.name,f.desc,f.family+(repeat>1?' يظهر في '+repeat+' مواقع.':''),f.hours);showSheet();}
function currentRooms(){if(state.resort==='park'&&state.mapKind==='official')return officialRooms;if(state.resort==='blu')return complexRooms.filter(r=>!['N','O'].includes(r.code));return complexRooms.filter(r=>['N','O'].includes(r.code));}
function showRoom(code){const r=currentRooms().find(z=>z.code===code);if(!r)return;$$('.marker').forEach(m=>m.classList.toggle('selected',m.dataset.code===code));const title=code==='أجنحة'?'الأجنحة':'المبنى '+code,desc=state.mapKind==='official'?'التقسيم ونطاق الغرف مأخوذان من الخريطة الرسمية الجديدة لأكوا بارك.':'الحرف يحدد نطاق غرف في خريطة المجمع.';if(els.detail)els.detail.innerHTML='<div class="detail-symbol room-symbol">'+code+'</div><span class="pill">منطقة غرف</span><h2>'+title+'</h2><p>'+desc+'</p><div class="detail-row"><b>نطاق الغرف</b>'+r.rooms+'</div><div class="detail-row"><b>طلب العائلة</b>غرفتان متجاورتان في الدور الأرضي، قريبتان من مرافق الأطفال والمطاعم وبعيدتان عن الضوضاء، حسب التوفر.</div>';fillSheet(code,'منطقة غرف',title,desc,'نطاق الغرف: '+r.rooms,'التخصيص النهائي حسب توفر الفندق');showSheet();}
function clearMarkers(){els.stage.querySelectorAll('.marker').forEach(m=>m.remove());}
function addMarker({number,code,x,y,official=false,room=false,label}){const b=document.createElement('button');b.type='button';b.className='marker'+(official?' official-hit':'')+(room?' room':'');b.style.left=x+'%';b.style.top=y+'%';if(number!==undefined){b.dataset.number=number;b.textContent=official?'':String(number);b.setAttribute('aria-label','عرض المرفق رقم '+number);b.addEventListener('click',e=>{e.stopPropagation();showFacility(number);});}else{b.dataset.code=code;b.textContent=label||code;b.setAttribute('aria-label','عرض منطقة الغرف '+code);b.addEventListener('click',e=>{e.stopPropagation();showRoom(code);});}els.stage.appendChild(b);}
function renderMarkers(){clearMarkers();if(state.mapKind==='official'){if(state.mode==='facilities')officialPx.forEach(([n,x,y])=>addMarker({number:n,x,y,official:true}));else officialRooms.forEach(r=>addMarker({code:r.code,x:r.x,y:r.y,room:true,label:r.code==='أجنحة'?'جناح':r.code}));return;}if(state.mode==='facilities')(complexHotspots[state.resort]||[]).forEach(([n,x,y])=>addMarker({number:n,x,y}));else currentRooms().forEach(r=>addMarker({code:r.code,x:r.x,y:r.y,room:true}));}
function setMode(mode){state.mode=mode;const f=$('#facilityModeBtn'),r=$('#roomModeBtn');if(f)f.classList.toggle('active',mode==='facilities');if(r)r.classList.toggle('active',mode==='rooms');renderMarkers();if(els.detail)els.detail.innerHTML=mode==='facilities'?'<span class="pill">أرقام المرافق</span><h2>اضغط على أي رقم</h2><p>سيظهر اسم المرفق ووصفه ومعلوماته وأوقات تشغيله.</p>':'<span class="pill">مناطق الغرف</span><h2>اضغط على رمز المبنى</h2><p>سيظهر نطاق أرقام الغرف والمعلومات المرتبطة بالمبنى.</p>';renderFilters();renderFacilityGrid();renderRooms();}
const facilityBtn=$('#facilityModeBtn'),roomBtn=$('#roomModeBtn');if(facilityBtn)facilityBtn.addEventListener('click',()=>setMode('facilities'));if(roomBtn)roomBtn.addEventListener('click',()=>setMode('rooms'));
function currentFacilities(){if(state.mapKind==='official')return officialFacilities;const allowed=new Set((complexHotspots[state.resort]||[]).map(h=>h[0]));return baseFacilities.filter(f=>allowed.has(f.n));}
function renderFilters(){if(!els.filters)return;const cats=['الكل',...new Set(currentFacilities().map(f=>f.cat))];if(!cats.includes(state.category))state.category='الكل';els.filters.innerHTML='';cats.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='filter'+(state.category===c?' active':'');b.textContent=c;b.addEventListener('click',()=>{state.category=c;renderFilters();renderFacilityGrid();});els.filters.appendChild(b);});}
function renderFacilityGrid(){if(!els.grid)return;const q=els.search?els.search.value.trim():'',list=currentFacilities().filter(f=>(state.category==='الكل'||f.cat===state.category)&&(!q||(String(f.n)+' '+f.name+' '+f.cat+' '+f.desc).includes(q)));els.grid.innerHTML='';if(!list.length){els.grid.innerHTML='<div class="card empty">لا توجد نتائج مطابقة.</div>';return;}list.forEach(f=>{const card=document.createElement('article');card.className='card facility';card.innerHTML='<div class="facility-top"><div class="facility-num">'+f.n+'</div><div><span class="pill">'+f.cat+'</span><h3>'+f.name+'</h3></div></div><p>'+f.desc+'</p><div class="hour '+(f.confirmed?'ok':'')+'">'+f.hours+'</div>';card.addEventListener('click',()=>{openView('mapView');setMode('facilities');const h=state.mapKind==='official'?officialPx.find(x=>x[0]===f.n):(complexHotspots[state.resort]||[]).find(x=>x[0]===f.n);if(h){setZoom(innerWidth<700?2.2:1.7,false);centerAt(h[1],h[2]);}setTimeout(()=>showFacility(f.n),180);});els.grid.appendChild(card);});}
if(els.search)els.search.addEventListener('input',renderFacilityGrid);
function renderEvents(){if(!els.events)return;els.events.innerHTML='';baseSchedules.forEach(e=>{const c=document.createElement('article');c.className='card event';c.innerHTML='<h3>'+e.name+'</h3><div class="time">'+e.time+'</div><span class="status '+(e.verified?'':'warn')+'">'+(e.verified?'مؤكد رسميًا':'يحتاج تأكيدًا')+'</span><p>'+e.note+'</p>';els.events.appendChild(c);});}
function renderRooms(){if(!els.rooms)return;els.rooms.innerHTML='';currentRooms().forEach(r=>{const b=document.createElement('button');b.type='button';b.className='room-card';b.innerHTML='<strong class="room-code">'+(r.code==='أجنحة'?'ج':r.code)+'</strong><div><b>'+(r.code==='أجنحة'?'الأجنحة':'المبنى '+r.code)+'</b><span>الغرف '+r.rooms+'</span></div>';b.addEventListener('click',()=>{openView('mapView');setMode('rooms');setZoom(innerWidth<700?2.15:1.65,false);centerAt(r.x,r.y);setTimeout(()=>showRoom(r.code),180);});els.rooms.appendChild(b);});const rec=$('#roomRecommendation');if(rec)rec.textContent=state.resort==='park'&&state.mapKind==='official'?'المباني الرسمية في أكوا بارك: A وB وC وD، إضافة إلى الأجنحة. اطلب غرفتين متجاورتين بالدور الأرضي، ويُحدد المبنى حسب التوفر.':'اطلب الدور الأرضي والغرف المتجاورة، مع مراعاة القرب من مرافق الأسرة والبعد عن الضوضاء.';}
function mapSource(kind){if(kind==='official'&&window.AQUAPARK_MAP_B64)return'data:image/webp;base64,'+window.AQUAPARK_MAP_B64;return'map-v10.webp?v=17';}
function setImage(kind,after){state.mapKind=kind;state.imageToken+=1;const token=state.imageToken;clearMarkers();els.stage.classList.toggle('official-map',kind==='official');let completed=false;const done=()=>{if(completed||token!==state.imageToken)return;completed=true;setZoom(1,false);els.viewport.scrollLeft=0;els.viewport.scrollTop=0;renderMarkers();renderFilters();renderFacilityGrid();renderRooms();if(after)after();};els.image.onload=done;els.image.onerror=()=>{const notice=$('#mapNotice');if(notice)notice.innerHTML='<b>تعذر تحميل صورة الخريطة.</b> أعد فتح الصفحة.';};els.image.src=mapSource(kind);if(els.image.complete&&els.image.naturalWidth)requestAnimationFrame(done);}
function updateHeader(){const c=config[state.resort],name=$('#currentResortName');if(name)name.textContent=c.name+(state.mapKind==='official'?' — الخريطة الرسمية':' — خريطة المجمع');const pools=$('#statPools'),heated=$('#statHeated'),rest=$('#statRestaurants'),bars=$('#statBars');if(pools)pools.textContent=c.pools;if(heated)heated.textContent=c.heated;if(rest)rest.textContent=state.mapKind==='official'?3:(state.resort==='blu'?8:7);if(bars)bars.textContent=state.mapKind==='official'?5:(state.resort==='blu'?12:8);}
function updateToolbar(){const a=$('#areaPrimary'),b=$('#areaSecondary'),full=$('#areaFull'),notice=$('#mapNotice');if(state.resort==='park'){if(a)a.textContent='الخريطة الرسمية';if(b)b.textContent='مناطق الغرف';if(full)full.textContent='المجمع كاملًا';if(notice)notice.innerHTML=state.mapKind==='official'?'<b>الخريطة الرسمية الجديدة لأكوا بارك.</b> اضغط مباشرة على أي رقم مطبوع في الخريطة لعرض اسم المرفق ومعلوماته.':'<b>خريطة المجمع الكاملة.</b> تعرض العلاقة بين أكوا بارك وأكوا بلو والمرافق المشتركة.';}else{if(a)a.textContent='وسط أكوا بلو';if(b)b.textContent='ألف ليلة وليلة';if(full)full.textContent='الخريطة كاملة';if(notice)notice.innerHTML='<b>خريطة أكوا بلو والمجمع.</b> اضغط على العلامات الحمراء لعرض تفاصيل المرافق.';}updateHeader();}
function chooseParkOfficial(mode='facilities'){state.resort='park';state.lastArea=mode==='rooms'?'rooms':'official';state.category='الكل';setImage('official',()=>{setMode(mode);updateToolbar();openView('mapView');if(mode==='rooms')focusPoint([44,56,1.25]);});}
function chooseComplex(resort,focus){state.resort=resort;state.lastArea=focus||'full';state.category='الكل';setImage('complex',()=>{setMode('facilities');updateToolbar();openView('mapView');if(resort==='blu'&&focus==='primary')focusPoint([43,48,2.35]);else if(resort==='blu'&&focus==='secondary')focusPoint([23,42,2.45]);else if(resort==='park'&&focus==='park')focusPoint([72,46,2.2]);else focusPoint([50,45,1]);});}
function switchResort(resort){state.resort=resort;$$('.resort-btn').forEach(b=>b.classList.toggle('active',b.dataset.resort===resort));if(resort==='park')chooseParkOfficial('facilities');else chooseComplex('blu','primary');}
$$('.resort-btn').forEach(b=>b.addEventListener('click',()=>switchResort(b.dataset.resort)));
const primary=$('#areaPrimary'),secondary=$('#areaSecondary'),full=$('#areaFull');if(primary)primary.addEventListener('click',()=>{if(state.resort==='park')chooseParkOfficial('facilities');else chooseComplex('blu','primary');});if(secondary)secondary.addEventListener('click',()=>{if(state.resort==='park')chooseParkOfficial('rooms');else chooseComplex('blu','secondary');});if(full)full.addEventListener('click',()=>chooseComplex(state.resort,state.resort==='park'?'park':'full'));
const zoomIn=$('#zoomIn'),zoomOut=$('#zoomOut'),reset=$('#resetMap');if(zoomIn)zoomIn.addEventListener('click',()=>setZoom(state.zoom+.35));if(zoomOut)zoomOut.addEventListener('click',()=>setZoom(state.zoom-.35));if(reset)reset.addEventListener('click',()=>{if(state.mapKind==='official')focusPoint(state.mode==='rooms'?[44,56,1.25]:[50,50,1]);else if(state.resort==='blu'&&state.lastArea==='primary')focusPoint([43,48,2.35]);else if(state.resort==='blu'&&state.lastArea==='secondary')focusPoint([23,42,2.45]);else focusPoint([50,45,1]);});
function distance(a,b){const dx=a.clientX-b.clientX,dy=a.clientY-b.clientY;return Math.sqrt(dx*dx+dy*dy);}let pinchDistance=0,pinchZoom=1;els.viewport.addEventListener('touchstart',e=>{if(e.touches.length===2){pinchDistance=distance(e.touches[0],e.touches[1]);pinchZoom=state.zoom;}},{passive:true});els.viewport.addEventListener('touchmove',e=>{if(e.touches.length===2&&pinchDistance){e.preventDefault();setZoom(pinchZoom*distance(e.touches[0],e.touches[1])/pinchDistance);}},{passive:false});els.viewport.addEventListener('touchend',e=>{if(e.touches.length<2)pinchDistance=0;},{passive:true});
renderEvents();switchResort('park');
})();
