(function(){
'use strict';
if(typeof F==='undefined'||typeof H==='undefined'||typeof S==='undefined'){
 document.body.innerHTML='<main style="padding:24px;font-family:Tahoma;text-align:center">تعذر تحميل بيانات الخريطة. أعد فتح الصفحة.</main>';
 return;
}
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const facilities=F.map(([n,name,cat,desc,family,hours,confirmed])=>({n,name,cat,desc,family,hours,confirmed:!!confirmed}));
const schedules=S.map(([name,time,verified,note])=>({name,time,verified:!!verified,note}));
const counts=new Map();H.forEach(h=>counts.set(h[0],(counts.get(h[0])||0)+1));
function uniqueByNumber(list){const seen=new Set();return list.filter(h=>{if(seen.has(h[0]))return false;seen.add(h[0]);return true})}
const resortHotspots={park:uniqueByNumber(H.filter(h=>h[1]>=57)),blu:uniqueByNumber(H.filter(h=>h[1]<=60))};
const roomZones=[
 {code:'A',rooms:'1001–1122',x:50.7,y:22},{code:'B',rooms:'2001–2114',x:61.1,y:34},{code:'C',rooms:'2115–2170',x:50.2,y:42},{code:'D',rooms:'3001–3081',x:58.7,y:55},{code:'E',rooms:'4001–4081',x:58.7,y:84},{code:'F',rooms:'4082–4093',x:67.7,y:92},{code:'G',rooms:'5001–5085',x:43.3,y:88},{code:'H',rooms:'5101–5151',x:27.2,y:66},{code:'I',rooms:'5401–5500',x:16.5,y:72},{code:'J',rooms:'5601–5638',x:31.8,y:40},{code:'K',rooms:'5639–5665',x:32.1,y:27},{code:'L',rooms:'5666–5692',x:33.9,y:28},{code:'M',rooms:'5801–5864',x:34.7,y:49},{code:'N',rooms:'6001–6053',x:73.5,y:32},{code:'O',rooms:'7001–7076',x:67.2,y:52},{code:'P',rooms:'120–144 و216–245',x:17.8,y:20},{code:'Q',rooms:'148–171 و246–268',x:15.5,y:32},{code:'R',rooms:'109–119 و145–147 و172–181 و205–215 و270–278',x:11.8,y:27},{code:'S',rooms:'501–590',x:22.9,y:31},{code:'T',rooms:'301–361',x:28,y:28}
];
const config={
 park:{name:'بيكالباتروس أكوا بارك',short:'أكوا بارك',pools:25,heated:4,restaurants:7,bars:8,primary:[76,42,2.55],secondary:[68,54,2.55],primaryLabel:'الألعاب المائية',secondaryLabel:'غرف أكوا بارك',rooms:new Set(['N','O']),recommend:'المنطقة O — الغرف 7001–7076، ثم المنطقة N — الغرف 6001–6053.'},
 blu:{name:'بيكالباتروس أكوا بلو',short:'أكوا بلو',pools:25,heated:4,restaurants:8,bars:12,primary:[43,48,2.35],secondary:[23,42,2.45],primaryLabel:'وسط أكوا بلو',secondaryLabel:'ألف ليلة وليلة',rooms:new Set(['A','B','C','D','E','F','G','H','I','J','K','L','M','P','Q','R','S','T']),recommend:'اختر المبنى بحسب قربه من المسبح والمطاعم، ثم اطلب الدور الأرضي وتجنب مناطق العروض المباشرة.'}
};
const state={resort:'park',mode:'facilities',zoom:1,lastArea:'primary',category:'الكل'};
const els={stage:$('#stage'),viewport:$('#viewport'),detail:$('#detail'),sheet:$('#sheet'),zoom:$('#zoomInfo'),grid:$('#facilityGrid'),filters:$('#filters'),search:$('#search'),events:$('#eventGrid'),rooms:$('#roomGrid')};
function openView(id){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));window.scrollTo({top:0,behavior:'smooth'})}
$$('.tab').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.view)));
function setZoom(value,keepCenter=true){const oldW=els.stage.scrollWidth||els.viewport.clientWidth;const cx=els.viewport.scrollLeft+els.viewport.clientWidth/2,cy=els.viewport.scrollTop+els.viewport.clientHeight/2;state.zoom=Math.max(1,Math.min(4,value));els.stage.style.width=(state.zoom*100)+'%';els.zoom.textContent='التكبير: '+Math.round(state.zoom*100)+'٪';if(keepCenter)requestAnimationFrame(()=>{const ratio=els.stage.scrollWidth/oldW;els.viewport.scrollLeft=Math.max(0,cx*ratio-els.viewport.clientWidth/2);els.viewport.scrollTop=Math.max(0,cy*ratio-els.viewport.clientHeight/2)})}
function centerAt(x,y){requestAnimationFrame(()=>{els.viewport.scrollLeft=Math.max(0,els.stage.scrollWidth*x/100-els.viewport.clientWidth/2);els.viewport.scrollTop=Math.max(0,els.stage.scrollHeight*y/100-els.viewport.clientHeight/2)})}
function focusPoint(point){const [x,y,z]=point;setZoom(innerWidth<700?z:Math.max(1.55,z-0.7),false);setTimeout(()=>centerAt(x,y),30)}
function facilityByNumber(n){return facilities.find(f=>f.n===n)}
function currentRooms(){return roomZones.filter(r=>config[state.resort].rooms.has(r.code))}
function showSheet(){if(innerWidth<=850){els.sheet.classList.add('open');els.sheet.setAttribute('aria-hidden','false')}}
function closeSheet(){els.sheet.classList.remove('open');els.sheet.setAttribute('aria-hidden','true')}
$('#closeSheet').addEventListener('click',closeSheet);els.sheet.addEventListener('click',e=>{if(e.target===els.sheet)closeSheet()});
function fillSheet(symbol,cat,title,desc,extra,status){$('#sheetNumber').textContent=symbol;$('#sheetCat').textContent=cat;$('#sheetTitle').textContent=title;$('#sheetDesc').textContent=desc;$('#sheetFamily').textContent=extra;$('#sheetHours').textContent=status}
function showFacility(n){const f=facilityByNumber(n);if(!f)return;$$('.marker').forEach(m=>m.classList.toggle('selected',m.dataset.number===String(n)));const repeat=counts.get(n)||1;els.detail.innerHTML='<div class="detail-symbol">'+n+'</div><span class="pill">'+f.cat+'</span><h2>'+f.name+'</h2><p>'+f.desc+'</p><div class="detail-row"><b>مناسبته للعائلة</b>'+f.family+'</div><div class="detail-row"><b>أوقات التشغيل</b><span class="hour '+(f.confirmed?'ok':'')+'">'+f.hours+'</span></div>'+(repeat>1?'<div class="detail-row"><b>تعدد المواقع</b>المرفق موجود في '+repeat+' مواقع بالمخطط الأصلي؛ تظهر هنا علامة واحدة فقط.</div>':'');fillSheet(n,f.cat,f.name,f.desc,f.family+(repeat>1?' المرفق موجود في '+repeat+' مواقع.':''),f.hours);showSheet()}
function showRoom(code){const r=roomZones.find(z=>z.code===code);if(!r)return;$$('.marker').forEach(m=>m.classList.toggle('selected',m.dataset.code===code));els.detail.innerHTML='<div class="detail-symbol">'+r.code+'</div><span class="pill">منطقة غرف</span><h2>المبنى '+r.code+'</h2><p>الحرف يحدد مبنى أو نطاق غرف داخل المنتجع.</p><div class="detail-row"><b>نطاق الغرف</b>'+r.rooms+'</div><div class="detail-row"><b>الاستخدام</b>اذكر الحرف ونطاق الغرف عند إرسال طلبك للفندق.</div>';fillSheet(r.code,'منطقة غرف','المبنى '+r.code,'الحرف يحدد منطقة غرف داخل المنتجع.','نطاق الغرف: '+r.rooms,'لا ينطبق');showSheet()}
function renderMarkers(){els.stage.querySelectorAll('.marker').forEach(m=>m.remove());const data=state.mode==='facilities'?resortHotspots[state.resort]:currentRooms().map(r=>[r.code,r.x,r.y]);data.forEach(item=>{const b=document.createElement('button');b.type='button';b.className='marker'+(state.mode==='rooms'?' room':'');if(state.mode==='facilities'){const [n,x,y]=item;b.textContent=n;b.dataset.number=n;b.style.left=x+'%';b.style.top=y+'%';b.setAttribute('aria-label','عرض المرفق رقم '+n);b.addEventListener('click',e=>{e.stopPropagation();showFacility(n)})}else{const [code,x,y]=item;b.textContent=code;b.dataset.code=code;b.style.left=x+'%';b.style.top=y+'%';b.setAttribute('aria-label','عرض منطقة الغرف '+code);b.addEventListener('click',e=>{e.stopPropagation();showRoom(code)})}els.stage.appendChild(b)})}
function setMode(mode){state.mode=mode;$('#facilityModeBtn').classList.toggle('active',mode==='facilities');$('#roomModeBtn').classList.toggle('active',mode==='rooms');renderMarkers();els.detail.innerHTML=mode==='facilities'?'<span class="pill">أرقام المرافق</span><h2>اضغط على أي رقم</h2><p>ستظهر تفاصيل المرفق مباشرة. كل رقم يظهر مرة واحدة فقط.</p>':'<span class="pill">حروف الغرف</span><h2>اضغط على أي حرف</h2><p>ستظهر منطقة المبنى ونطاق أرقام الغرف التابعة له.</p>'}
$('#facilityModeBtn').addEventListener('click',()=>setMode('facilities'));$('#roomModeBtn').addEventListener('click',()=>setMode('rooms'));
function currentAllowedNumbers(){return new Set(resortHotspots[state.resort].map(h=>h[0]))}
function renderFilters(){const allowed=currentAllowedNumbers();const cats=['الكل',...new Set(facilities.filter(f=>allowed.has(f.n)).map(f=>f.cat))];if(!cats.includes(state.category))state.category='الكل';els.filters.innerHTML='';cats.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='filter'+(state.category===c?' active':'');b.textContent=c;b.addEventListener('click',()=>{state.category=c;renderFilters();renderFacilityGrid()});els.filters.appendChild(b)})}
function renderFacilityGrid(){const allowed=currentAllowedNumbers();const q=els.search.value.trim();const list=facilities.filter(f=>allowed.has(f.n)&&(state.category==='الكل'||f.cat===state.category)&&(!q||(String(f.n)+' '+f.name+' '+f.cat+' '+f.desc).includes(q)));els.grid.innerHTML='';if(!list.length){els.grid.innerHTML='<div class="card empty">لا توجد نتائج مطابقة.</div>';return}list.forEach(f=>{const card=document.createElement('article');card.className='card facility';card.innerHTML='<div class="facility-top"><div class="facility-num">'+f.n+'</div><div><span class="pill">'+f.cat+'</span><h3>'+f.name+'</h3></div></div><p>'+f.desc+'</p><div class="hour '+(f.confirmed?'ok':'')+'">'+f.hours+'</div>';card.addEventListener('click',()=>{openView('mapView');setMode('facilities');const h=resortHotspots[state.resort].find(x=>x[0]===f.n);if(h){setZoom(innerWidth<700?2.8:2,false);centerAt(h[1],h[2])}setTimeout(()=>showFacility(f.n),160)});els.grid.appendChild(card)})}
els.search.addEventListener('input',renderFacilityGrid);
function renderEvents(){els.events.innerHTML='';schedules.forEach(e=>{const c=document.createElement('article');c.className='card event';c.innerHTML='<h3>'+e.name+'</h3><div class="time">'+e.time+'</div><span class="status '+(e.verified?'':'warn')+'">'+(e.verified?'مؤكد رسميًا':'يحتاج تأكيدًا')+'</span><p>'+e.note+'</p>';els.events.appendChild(c)})}
function renderRooms(){els.rooms.innerHTML='';currentRooms().forEach(r=>{const b=document.createElement('button');b.type='button';b.className='room-card';b.innerHTML='<strong class="room-code">'+r.code+'</strong><div><b>المبنى '+r.code+'</b><span>الغرف '+r.rooms+'</span></div>';b.addEventListener('click',()=>{openView('mapView');setMode('rooms');setZoom(innerWidth<700?2.8:2,false);centerAt(r.x,r.y);setTimeout(()=>showRoom(r.code),160)});els.rooms.appendChild(b)});$('#roomRecommendation').textContent=config[state.resort].recommend}
function switchResort(resort){state.resort=resort;const c=config[resort];$$('.resort-btn').forEach(b=>b.classList.toggle('active',b.dataset.resort===resort));$('#currentResortName').textContent=c.name;$('#statPools').textContent=c.pools;$('#statHeated').textContent=c.heated;$('#statRestaurants').textContent=c.restaurants;$('#statBars').textContent=c.bars;$('#areaPrimary').textContent=c.primaryLabel;$('#areaSecondary').textContent=c.secondaryLabel;$('#mapNotice').innerHTML='<b>أنت الآن في خريطة '+c.short+'.</b> جميع الأزرار والأرقام والحروف قابلة للضغط.';state.category='الكل';setMode('facilities');renderFilters();renderFacilityGrid();renderEvents();renderRooms();openView('mapView');state.lastArea='primary';focusPoint(c.primary)}
$$('.resort-btn').forEach(b=>b.addEventListener('click',()=>switchResort(b.dataset.resort)));
$('#areaPrimary').addEventListener('click',()=>{state.lastArea='primary';focusPoint(config[state.resort].primary)});$('#areaSecondary').addEventListener('click',()=>{state.lastArea='secondary';focusPoint(config[state.resort].secondary)});$('#areaFull').addEventListener('click',()=>{state.lastArea='full';focusPoint([50,45,1])});$('#zoomIn').addEventListener('click',()=>setZoom(state.zoom+.35));$('#zoomOut').addEventListener('click',()=>setZoom(state.zoom-.35));$('#resetMap').addEventListener('click',()=>focusPoint(state.lastArea==='primary'?config[state.resort].primary:state.lastArea==='secondary'?config[state.resort].secondary:[50,45,1]));
function distance(a,b){const dx=a.clientX-b.clientX,dy=a.clientY-b.clientY;return Math.sqrt(dx*dx+dy*dy)}let pinchDistance=0,pinchZoom=1;els.viewport.addEventListener('touchstart',e=>{if(e.touches.length===2){pinchDistance=distance(e.touches[0],e.touches[1]);pinchZoom=state.zoom}},{passive:true});els.viewport.addEventListener('touchmove',e=>{if(e.touches.length===2&&pinchDistance){e.preventDefault();setZoom(pinchZoom*distance(e.touches[0],e.touches[1])/pinchDistance)}},{passive:false});els.viewport.addEventListener('touchend',e=>{if(e.touches.length<2)pinchDistance=0},{passive:true});
$('#mapImage').addEventListener('load',()=>switchResort('park'));$('#mapImage').addEventListener('error',()=>{$('#mapNotice').innerHTML='<b>تعذر تحميل صورة الخريطة.</b> أعد فتح الصفحة.'});
renderEvents();
})();
